### ISSUE TITLE
[Bug] Broke "Deposit All" actions

### ISSUE THREAD

**Issue by The-KingJoshington** [Ciarenni/COTL_MysticAssistant#1]
Your last update (where you added more options to the assistant) has broken the "Deposit All" functions for seed & fertilizer silos. It's also disrupted any "collect all" options from the QoL mods. 
Disabling your mod fixes this problem and the problem appeared as soon as you pushed your last update.

**Comment by Ciarenni** [comment]
I was able to reproduce the issue with "Deposit All" and pushed a new version that has fixed it, at least on my end. I do not have any QoL mods to verify that those are also fixed, but I am rather confident that this will fix those as well. This was an issue I had previously fixed but re-introduced with a lapse of focus. The fix for it was ultimately the same as before, thus my confidence that it should be working with other mods once more.

Thanks for filing this issue, it let me address this pretty quickly. I'm going to close this ticket, but if the QoL mods are still not working after this, please open a new ticket and which specific mods you have installed so that I can investigate that issue!
